### ISSUE TITLE
List of unit tests that need to be added

### ISSUE THREAD

**Issue by daikikatsuragawa** [pycaret/pycaret#337]
- [x] test_arules.py  #338
- [x] test_datasets.py #365
- [x] test_nlp.py https://github.com/pycaret/pycaret/commit/773f14329a7ec8208aded68afae272c7808acfec
- [x] test_preprocess.py #409
- [x] test_utils.py #393

**Comment by pycaret** [comment]
@daikikatsuragawa Thanks for working on this. 

Will be waiting for rest of the tests.

**Comment by daikikatsuragawa** [comment]
I will proceed step by step. After completing the process, we will review each test and improve the quality.

**Comment by daikikatsuragawa** [comment]
@pycaret #365 

I propose two solutions to the `test_nlp.py` problem.

- Add `python -m spacy download en` to `.travis.yml`.
- Add `python -m spacy download en` to `.requirements.txt`.

**Comment by daikikatsuragawa** [comment]
For the time being, all Python files have been tested.

**Comment by pycaret** [comment]
@daikikatsuragawa Thank you so much.
